import Container from '@src/components/Container/container';
import Footer from '@src/components/Footer/footer';
import Header from '@src/components/Header/header';
import MenuCategory from '@src/components/MenuCategory/menuCategory';
import MovieCarousel from '@src/components/MovieCarousel/movieCarousel';
import withAuth from '@src/hook/withAuth';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { API_KEY } from 'pages/api/tmdb';
import { useEffect, useState } from 'react';

function SearchResults() {
  const router = useRouter();
  const { query } = router.query; // Obtem o termo da busca da URL
  const [results, setResults] = useState([]);
  const [error, setError] = useState('');

  useEffect(() => {
    if (query) {
      const fetchMovies = async () => {
        const url = `https://api.themoviedb.org/3/search/movie?api_key=${API_KEY}&query=${encodeURIComponent(query)}`;

        try {
          const response = await fetch(url);
          const data = await response.json();
          console.log(data);
          setResults(data);

          if (data.lenght === 0) {
            setError('Nenhum filme encontrado para a sua busca. Tente novamente com outra palavra-chave.');
          }
        } catch (error) {
          console.error('Erro na busca:', error);
        }
      };

      fetchMovies();
    }
  }, [query]);
  return (
    <>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
        <link href="https://fonts.googleapis.com/css2?family=Rubik+Gemstones&display=swap" rel="stylesheet"></link>
      </Head>

      <Header height="87vh" />
      <Container hasDegrade>
        <MovieCarousel items={results} />
        <MenuCategory title="Procurando uma categoria?" paddingTop="50px" />
      </Container>
      {error && <p>hdsjf</p>}
      <Footer />
    </>
  );
}

export default withAuth(SearchResults);
