import HeaderCategory from '@src/components/HeaderCategory/headerCategory';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function ActionCategory() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Filmes | Ação</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
        <link href="https://fonts.googleapis.com/css2?family=Rubik+Gemstones&display=swap" rel="stylesheet"></link>
      </Head>
      <main>
        <HeaderCategory id={1} />
        <p>Post: {router.query.action}</p>
      </main>
    </>
  );
}
