import Head from 'next/head';
import Button from '@src/components/Button/button';
import LoginForm from '@src/components/login/login';
import { Sinopse, Title } from '@src/components/Header/style';
import Container from '@src/components/Container/container';
import Box from '@src/shared/Box/box';
import Text from '@src/components/Text/text';
// import imageBackground from '../../../public/assets/images/aquaman.jpeg';

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>Bem vindo(a) ao MiraFlix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
        <link href="https://fonts.googleapis.com/css2?family=Rubik+Gemstones&display=swap" rel="stylesheet"></link>
      </Head>

      <Container
        backgroundImage={'/assets/images/streaming.jpg'}
        styleSheet={{
          height: '100vh',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          padding: '20px',
        }}
      >
        <Box tag="div" styleSheet={{ width: '50%' }}>
          <Title>Filmes, séries, esportes e muito mais</Title>
          <Sinopse>
            Assista a Amazon Originais premiados e aproveite entrega grátis e rápida em diversos produtos. Com o
            plano anual você parcela em até 12x de R$ 13,90/mês sem juros (R$ 166,80 por ano).
          </Sinopse>
        </Box>

        <Box
          tag="div"
          styleSheet={{
            background: 'black',
            width: '310px',
            height: '350px',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            borderRadius: '17px',
          }}
        >
          <LoginForm />
          <Box
            styleSheet={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              padding: '10px',
              gap: '10px',
            }}
          >
            <Text tag="h3">Ainda não tem cadastro?</Text>
            <Button href="/signup">cadastre-se</Button>
          </Box>
        </Box>
      </Container>
    </>
  );
}
