import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import api_tmdb from '../../pages/api/tmdb'; // Ajuste o caminho conforme necessário
import Head from 'next/head';
import { IList } from '@src/types/apiTypes';
import HeaderMovieDetails from '@src/components/HeaderMovieDetails/headerMovieDetails';

export default function MovieDetails() {
  const router = useRouter();
  const [movie, setMovie] = useState<IList[] | null>(null);

  // returns data for a single movie
  useEffect(() => {
    const fetchMovieDetails = async () => {
      if (router.query.id) {
        console.log('ID:', router.query.id);
        const details = await api_tmdb.getMovieDetails(Number(router.query.id));
        console.log('Received movie details:', details);
        setMovie(details);
      }
    };

    fetchMovieDetails();
  }, [router.query.id]);

  return (
    <>
      <Head>
        <title>{`Filme | ID.${router.query.id}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
        <link href="https://fonts.googleapis.com/css2?family=Rubik+Gemstones&display=swap" rel="stylesheet"></link>
      </Head>
      {movie && <HeaderMovieDetails items={{ results: [movie], id: movie.id }} id={router.query.id} />}
    </>
  );
}
