import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import api_tmdb from '../../pages/api/tmdb'; // Ajuste o caminho conforme necessário
import Head from 'next/head';
import { Results } from '@src/types/apiTypes';
import HeaderMovieDetails from '@src/components/MovieDetails/movieDetails';
import Container from '@src/components/Container/container';
import withAuth from '@src/hook/withAuth';

function MovieDetails() {
  const router = useRouter();
  const [movie, setMovie] = useState<Results | null>(null);

  // returns data for a single movie
  useEffect(() => {
    const fetchMovieDetails = async () => {
      if (router.query.id) {
        const details = await api_tmdb.getMovieDetails(Number(router.query.id));
        setMovie(details);
      }
    };

    fetchMovieDetails();
  }, [router.query.id]);

  return (
    <>
      <Head>
        <title>{`Filme | ID.${router.query.id}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_popcorn.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
        <link href="https://fonts.googleapis.com/css2?family=Rubik+Gemstones&display=swap" rel="stylesheet"></link>
      </Head>

      {movie && (
        <Container hasDegrade>
          <HeaderMovieDetails items={{ results: [movie], id: movie.id ?? 0 }} id={router.query.id as string} />
        </Container>
      )}
    </>
  );
}

export default withAuth(MovieDetails);
