import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import api_tmdb from '../../pages/api/tmdb'; // Ajuste o caminho conforme necessário
import Head from 'next/head';
import { IList } from '@src/types/apiTypes';
import HeaderMovieDetails from '@src/components/HeaderMovieDetails/headerMovieDetails';

export default function MovieDetails() {
  const router = useRouter();
  const [movies, setMovies] = useState<IList[]>([]);

  useEffect(() => {
    const showResults = async () => {
      const list = await api_tmdb.getHomeList();
      setMovies(list);
    };

    showResults();
  }, []);

  return (
    <>
      <Head>
        <title>{`Filme | ID.${router.query.id}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
        <link href="https://fonts.googleapis.com/css2?family=Rubik+Gemstones&display=swap" rel="stylesheet"></link>
      </Head>

      {movies.map((movie) => (
        <HeaderMovieDetails key={Number(movie.id)} items={movie.items} id={router.query.id} />
      ))}
      {/* <div>
        <h1>{movie.title}</h1>
        <MediaImage
          src={`https://image.tmdb.org/t/p/w300${movie.poster_path}`}
          alt={movie.title}
          width={300}
          height={450}
        />
        <p>{movie.overview}</p>
      </div> */}
    </>
  );
}
