import Head from 'next/head';
import tmdp from '../../../pages/api/tmdb';
import { useEffect } from 'react';

export default function HomeScreen() {
  useEffect(() => {
    const showResults = async () => {
      const list = await tmdp.getHomeList();
      console.log(list);
    };
    showResults();
  }, []);

  return (
    <>
      <Head>
        <title>New Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>teste</div>
        <div></div>
      </main>
    </>
  );
}
