import NavBar from '@src/components/NavBar/NavBar';
import Text from '@src/components/Text/Text';
import theme from '@src/styles/themes';
import Head from 'next/head';

export default function HomeScreen() {
  return (
    <>
      <Head>
        <title>New Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Text tag="p" styleSheet={{ fontFamily: theme.tipography.font1.fontFamily, color: 'white' }}>
        TextComponents
      </Text>
    </>
  );
}
