import Head from 'next/head';
import Container from '@src/components/Container/container';
import SignupForm from '@src/components/SignupForm/signupForm';
import { Title } from '@src/components/Header/style';
import { FormArea, Subtitle, TextArea } from '../Login/style';
import Button from '@src/components/Button/button';

export default function SignupPage() {
  return (
    <>
      <Head>
        <title>Bem vindo(a) ao MiraFlix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_popcorn.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
        <link href="https://fonts.googleapis.com/css2?family=Rubik+Gemstones&display=swap" rel="stylesheet"></link>
      </Head>

      <Container
        backgroundImage={'/assets/images/login_capa.jpg'}
        hasBackgroundSizeCover
        styleSheet={{
          height: '100vh',
          display: 'flex',
          justifyContent: 'space-around',
          alignItems: 'center',
          padding: '5px',
          overflow: 'hidden',
        }}
      >
        <TextArea>
          <Title>Filmes, séries, documentários e muito mais...</Title>
          <Subtitle>
            Assista aos originais MiraFlix e explore um mundo de histórias incríveis com acesso ilimitado a filmes,
            séries e muito mais. Curta seus títulos favoritos ou descubra novas paixões com a liberdade de assistir
            quando e onde quiser.
          </Subtitle>
        </TextArea>

        <FormArea>
          <SignupForm />
          <Button href={'/login'}>Voltar ao Login</Button>
        </FormArea>
      </Container>
    </>
  );
}
